@startuml
[*] --> DisableSecurity
DisableSecurity --> SendScan : securityDisabled
SendScan --> WaitResponse : ScanSent
WaitResponse --> SendScan : (responseTimeout and nbScanPrimaryChannel < 5)
WaitResponse --> Identify : scanResponseReceived
WaitResponse --> EnableSecurity : (responseTimeout and nbScanPrimaryChannel = 5)
Identify --> WaitIdentify : identifyRequestSent
WaitIdentify --> FactoryReset : identifyPeriodPast
FactoryReset --> EnableSecurity : factoryResetSent
EnableSecurity --> [*] : SecurityEnabled
@enduml
