@startuml
[*] --> ActiveEndpointDiscovery
ActiveEndpointDiscovery --> SimpleDescriptorDiscovery : ActiveEnpointResponse
SimpleDescriptorDiscovery --> SimpleDescriptorDiscovery : OtherDescriptorsToQuery
SimpleDescriptorDiscovery --> [*] : AllEndpointsDiscovered
@enduml
